# .pre-commit-config.yaml
repos:
  # Ruff for linting & formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9 # Use the latest stable tag
    hooks:
      - id: ruff
        args: [--fix]   # auto-fix lint issues on commit
      - id: ruff-format # replaces black/isort, ensures code formatting

  # Pre-commit’s built-in housekeeping hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
