name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:debian

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync dependencies
        run: uv sync

      - name: Run tests
        run: uv run coverage report